const Enum = {
  
  GS_IDLE: 1,
  GS_MENU: 2,
  GS_COUNTDOWN: 3,
  GS_SPAWN: 4,
  GS_BATTLE: 5,
  GS_VICTORY: 6,
  GS_DEFEAT: 7,
  GS_PAUSE_LISTEN: 8,
  GS_PAUSE: 9,
  GS_VIEW: 10,
  GS_ENDING: 11,

  //  Locations

  AREA_VILLAGE: 101,
  AREA_FOREST: 102,
  AREA_MISC: 103,

  LOC_BLUE_FOREST: 1,
  LOC_MAM: 2,
  LOC_ROSE_FOREST: 3,
  LOC_STORM: 4,
  LOC_MINES: 5,
  LOC_PLAINS: 6,
  LOC_GREEN_FOREST: 7,
  LOC_GREEN: 8,

  // Sprite States
  
  SS_READY: 1,
  SS_DEFEND: 2,
  SS_ATTACK: 3,
  SS_BACKSTEP: 4,
  SS_HURT: 5,
  SS_REBOUND: 6,
  SS_COOLDOWN: 7,
  SS_DEAD: 8,

  // Sprite AI modes

  SM_IDLE: 1,
  SM_ATTACK: 2,
  SM_CLOSE: 3,

  TT_PLAYER: 1,
  TT_INFANTRY: 2,
  TT_HEAVY_INFANTRY: 3,
  TT_LANCER: 4,
  TT_ADVISOR: 5,

  TEAM_ALLY: 1,
  TEAM_ENEMY: 2,
  TEAM_PLAYER: 3,

  ACT_IDLE: 1,
  ACT_GOTO_TARGET: 2,
  ACT_BATTLE_CHECK: 3,
  ACT_BATTLE_DECISION: 4,
  ACT_BATTLE_ACTION: 5,
  ACT_HURT: 6,
  ACT_REBOUND: 7,

  //  Story References

  STORY_0_INTRO: 0,
  STORY_1A_APPRENTICE: 1,
  STORY_1B_APPRENTICE: 2,
  STORY_1C_BLUEFOREST: 3,
  STORY_2A_CLAIM_BLUE: 4,
  STORY_2B_GO_EAST: 5,
  STORY_3_DESTROY_ROSE: 6,
  STORY_4_CLAIM_STORM: 7,

  ACT_GOTO_PLAYER: 101
}
export default Enum;