const Enum = {
  
  GS_IDLE: 1,
  GS_MENU: 2,
  GS_COUNTDOWN: 3,
  GS_SPAWN: 4,
  GS_BATTLE: 5,
  GS_VICTORY: 6,
  GS_DEFEAT: 7,
  GS_PAUSE_LISTEN: 8,
  GS_PAUSE: 9,
  GS_VIEW: 10,
  GS_ENDING: 11,

  //  Locations

  AREA_VILLAGE: 101,
  AREA_FOREST: 102,
  AREA_MISC: 103,

  LOC_BLUE_FOREST: 1,
  LOC_MAM: 2,
  LOC_ROSE_FOREST: 3,
  LOC_STORM: 4,
  LOC_MINES: 5,
  LOC_PLAINS: 6,
  LOC_GREEN_FOREST: 7,
  LOC_GREEN: 8,

  // Sprite States
  
  SS_READY: 1,
  SS_DEFEND: 2,
  SS_ATTACK: 3,
  SS_BACKSTEP: 4,
  SS_HURT: 5,
  SS_REBOUND: 6,
  SS_COOLDOWN: 7,
  SS_DEAD: 8,
  SS_REPELLED: 9,

  // Citizen States

  CS_IDLE: 1,
  CS_DIGGING: 2,
  CS_TALKING: 3,
  CS_TRAVELLING: 4,
  CS_BOWING: 5,
  CS_CHEERING: 6,

  CS_HUNGRY: 30,
  CS_SOCIAL: 31,
  CS_CONVERSATION: 32,
  CS_FORAGING: 33,
  CS_BATTLE_MODE: 34,

  // Tribes

  TRIBE_MAM: 1,
  TRIBE_BLUE_FOREST: 2,
  TRIBE_STORM: 3,
  TRIBE_WHITELEAF: 4,

  // Soldier

  TEAM_ALLY: 1,
  TEAM_ENEMY: 2,
  TEAM_PLAYER: 3,

  SOLDIER_BANDIT1: 101,
  SOLDIER_BANDIT2: 102,
  SOLDIER_RABID_BANDIT: 110,

  SOLDIER_RED1: 111,
  SOLDIER_RED2: 112,
  SOLDIER_RED3: 113,
  SOLDIER_REDFACE: 120,

  SOLDIER_GR1: 121,
  SOLDIER_FALLEN_CLOUD: 130,

  SOLDIER_WL_INFANTRY: 131,
  SOLDIER_WL_HEAVY: 132,
  SOLDIER_WL_LANCER: 133,
  SOLDIER_WL_GREEN_SWORD: 134,
  SOLDIER_WL_SPLIT_CLOVER: 135,

  SOLDIER_ALLY_INFANTRY1: 201,
  SOLDIER_ALLY_HEAVY1: 202,
  SOLDIER_ALLY_LANCER1: 203,
  SOLDIER_ALLY_WILDMAN: 204,

  SOLDIER_ALLY_HEAVY2: 205,

  SOLDIER_PLAYER: 1,
  SOLDIER_WILDMAN: 10,
  SOLDIER_BLUEMOON: 11,
  SOLDIER_NIGHTTRAIN: 12,
  SOLDIER_ARCHITECT: 13,
  SOLDIER_LUNAR: 14,

  //  Building Types

  BUILDING_GENERIC: 1,
  
  BUILDING_HOUSE: 100,
  BUILDING_TOWER: 101,

  //  Collectible types

  COLLECT_HEART: 1,
  COLLECT_POWER: 2,
  COLLECT_DEFENSE: 3,
  COLLECT_SPEED: 4,
  COLLECT_TROOPS: 5,

  //  Unique IDs

  ID_MOON_CHIEF: 1,
  ID_BLUE_MOON: 2,
  ID_NIGHT_TRAIN: 3,
  ID_LUNAR: 4,

  ID_HARVEST_MOON: 5,
  ID_MOON_GLOW: 6,
  ID_MOON_ROSE: 7,

  ID_GREEN_CHIEF: 8,
  ID_BOSS: 9

}
export default Enum;